### ISSUE TITLE
support auto environment.

### ISSUE THREAD

**Issue by youyongsong** [youyongsong/uam#28]
use `${ENVVAR}` format to declare auto environment.

for example, use the following manifests:
```
version: "0.0.1"
description: offical python app.
image: "python:3"
entrypoints:
  python:
    container_entrypoint: python
  pip:
    container_entrypoint: pip

configs:
  - host_path: ~/.pip
    container_path: /root/.pip

volumes:
  - path: /usr/local/lib/python3.6/site-packages
  - path: /usr/local/bin

environments:
  host_home_dir: ${HOME}
  b: 2
```
before python or pip wrapper starting the container, it will get the value of environment variable `HOME`，and transform the value into the container with name `host_home_dir`.
